spring:
  profiles:
    active: dev
---
server:
 port: 8201 
spring:
 profiles: dev
 application: 
  name: microservicecloud-config-client
eureka: 
 client: 
  serviceUrl: 
   defaultZone: http://eurekaServer01.com:7001/eureka/   
---
server:
 port: 8202
spring:
 profiles: dev
 application: 
  name: microservicecloud-config-client
eureka: 
 client: 
  serviceUrl: 
   defaultZone: http://eurekaServer01.com:7001/eureka/ 