spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.happiness.springcloud.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
spring:
  profiles: dev # 开发环境
  application:
    name: microservicecloud-config-provider-dept01			# ******服务名*******
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://106.13.21.186:3306/cloudDB01 #数据库连接地址，*****注意库名 db01***************
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eurekaServer01.com:7001/eureka/,http://eurekaServer02.com:7002/eureka/,http://eurekaServer03.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrix
    prefer-ip-address: true
    
info:
  app.name: happiness-microservicecloud
  company.name: www.happiness.com
  build.artifactId: $project.artifactId$
  
# 在被监控服务上添加暴露端点 
management: 
  endpoints: 
    web:
      exposure: 
        include: hystrix.stream
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.happiness.springcloud.entities  # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
spring:
  profiles: test
  application: 
    name: microservicecloud-config-provider-dept01
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://106.13.21.186:3306/cloudDB01          # 数据库名称
    username: root
    password: admin123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eurekaServer01.com:7001/eureka/,http://eurekaServer02.com:7002/eureka/,http://eurekaServer03.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8001-hystrix
    prefer-ip-address: true
    
info:
  app.name: happiness-microservicecloud
  company.name: www.happiness.com
  build.artifactId: $project.artifactId$
  
# 在被监控服务上添加暴露端点 
management: 
  endpoints: 
    web:
      exposure: 
        include: hystrix.stream